### ISSUE TITLE
HU05

### ISSUE THREAD

**Issue by TektiticEel9062** [TC3005B-562-2024/Docs#12]
**Historia de Usuario no. 5**

Como supervisor quiero observar los detalles específicos de cada agente perteneciente a mi contact center. 

- Criterios de aceptación:

FRONTEND
1. Se muestra el nombre del agente.
2. Se muestra id del agente.
3. Se muestra skill a la que pertenece el agente.
4. Se muestra el estado del agente.
5. Se muestran insights existentes del agente.
6. Se muestran los contactos activos y con los datos más relevantes.
7. En caso de que Contact Lens esté activado y el monitoreo de sentimientos este activo se mostrarán las  emociones detectadas en cada uno de los contactos.

BACKEND
1. Se regresa una respuesta del agente consultado con sus datos de identificación tales como id, nombre y arn.
2. La respuesta contiene las métricas del agente tales cómo:
a.  ABANDONMENT RATE
b.  AGENT SCHEDULE ADHERENCE
c.  AVG HANDLE TIME
d.  AVG QUEUE ANSWER TIME
e.  AVG_RESOLUTION_TIME
f.  PERCENT CASES FIRST CONTACT RESOLVED
g.  SERVICE LEVEL
h.  AGENT OCCUPANCY
3. En los datos regresados se encuentran las alertas por aceptar asociadas al agente ordenadas por prioridad y también las alertas de capacitación aceptadas y su progreso.
4. En caso de tener contactos activos estos se incluyen en los datos, al igual que sus estadísticas asociadas.
5. En caso de que Contact Lens esté activado y configurado se incluirá el análisis de sentimiento en cada uno de los contactos.

- Estimación de horas: 40 h.

- Endpoints: 
/agents/{agent_id}

- Componentes de React:
1. ItemSubitem para desplegar la información del agente y otro para sus respectivas métricas.
2. Tarjeta de Alerta.
3. Lista de Tarjetas de Alerta.
4. IndividualTrainingExpansionPanel para enlistar los trainings necesarios para el agente y su respectivo estado (completado o no) manipulable dependiendo de las acciones del usuario desde el front.

- Actividades:
- [x] HU05A01 Crear Componente de React ItemSubitem.
- [x] HU05A02 Crear Componente de React Tarjeta de Alerta.
- [x] HU05A03 Crear Componente de React Lista de Tarjetas de Alerta.
- [x] HU05A04 Crear Componente de React IndividualTrainingExpansionPanel.
- [x] HU05A05 Crear endpoint para estructurar los datos necesarios en el back para la correcta respuesta de regreso.
- [x] HU05A06 Crear endpoint que permita la manipulación de los datos que permitan actualizar el valor del training manipulado por el usuario desde el front, para actualizar su valor a nivel de back. 
- [x] HU05A07 Conectar componentes a endpoints creados.

**Comment by JourneyHM** [comment]
Historia de Usuario Actualizada
