### ISSUE TITLE
HU15

### ISSUE THREAD

**Issue by elyansan** [TC3005B-562-2024/Docs#9]
**Historia de Usuario no. 15**

Como supervisor quiero acceder a una vista individual por cola al hacer click en un cualquier píldora presente en las tarjetas de los agentes.

- Criterios de aceptación:

1. Se debe poder acceder a la pagina de Queue por medio de el componente de Pill
2. Se debe redirigir a la Queue con el id específico que contiene cada Pill.
3. La pantalla de Queue debe desplegar toda la información requerida.

- Estimación de horas: 48 h.

- Endpoints: 
/queues/{queueId}
/queues/min
/queues

- Componentes de React:
1. Pill.
2. Pantalla Queue.

- Actividades:
- [x] HU15A01 Crear los componentes necesarios para la pantalla de Queue.
- [x] HU15A02 Desplegar la información de la página de Queue
- [x] HU15A03 Crear el endpoint de queue/min para poder pasarle esa informacion a las pills 
- [x] HU15A04 Crear la conexión y navegación entre las pills y la página de Queue

**Comment by FranciscoSanchezz** [comment]
**Historia de Usuario no. 15**

Como supervisor quiero acceder a una vista individual por cola al hacer click en un cualquier píldora presente en las tarjetas de los agentes.

- Criterios de aceptación:

1. Se debe poder acceder a la pagina de Queue por medio de el componente de Pill
2. Se debe redirigir a la Queue con el id específico que contiene cada Pill.
3. La pantalla de Queue debe desplegar toda la información requerida.


- Estimación de horas: 48 h.

- Endpoints: 
/queues/{queueId}
/queues/min
/queues


- Componentes de React:
1. Pill.
2. Pantalla Queue.


- Actividades:
- [x] HU15A01 Crear los componentes necesarios para la pantalla de Queue.
- [x] HU15A02 Desplegar la información de la página de Queue
- [x] HU15A03 Crear el endpoint de queue/min para poder pasarle esa informacion a las pills 
- [x] HU15A04 Crear la conexión y navegación entre las pills y la página de Queue

**Comment by FranciscoSanchezz** [comment]
**Historia de Usuario no. 15**

Como supervisor quiero acceder a una vista individual por cola al hacer click en un cualquier píldora presente en las tarjetas de los agentes.

- Criterios de aceptación:

1. Se debe poder acceder a la pagina de Queue por medio de el componente de Pill
2. Se debe redirigir a la Queue con el id específico que contiene cada Pill.
3. La pantalla de Queue debe desplegar toda la información requerida.


- Estimación de horas: 48 h.

- Endpoints: 
/queues/{queueId}
/queues/min
/queues


- Componentes de React:
1. Pill.
2. Pantalla Queue.


- Actividades:
- [x] HU15A01 Crear los componentes necesarios para la pantalla de Queue.
- [x] HU15A02 Desplegar la información de la página de Queue
- [x] HU15A03 Crear el endpoint de queue/min para poder pasarle esa informacion a las pills 
- [x] HU15A04 Crear la conexión y navegación entre las pills y la página de Queue
